apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    name: mongodb
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      labels:
        name: mongodb
    spec:
      containers:
        - env:
            - name: MONGODB_USER
              valueFrom:
                configMapKeyRef:
                  key: MONGODB_USER
                  name: dev-mongodb-config-map
            - name: MONGODB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MONGODB_PASSWORD
                  name: dev-mongodb-config-map
            - name: MONGODB_ADMIN_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MONGODB_ADMIN_PASSWORD
                  name: dev-mongodb-config-map
            - name: MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MONGODB_DATABASE
                  name: dev-mongodb-config-map
          image: openshift/mongodb-24-centos7
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 27017
            timeoutSeconds: 1
          name: mongodb
          ports:
            - containerPort: 27017
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - '-i'
                - '-c'
                - >-
                  mongo 127.0.0.1:27017/$MONGODB_DATABASE -u $MONGODB_USER -p
                  $MONGODB_PASSWORD --eval="quit()"
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: 512Mi
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/mongodb/data
              name: mongodb-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb
  test: false
  triggers:
    - type: ConfigChange
