apiVersion: v1
data:
  APPNAME: National Parks (Dev)
  DB_HOST: mongodb
  DB_PORT: 27017
  DB_PASSWORD: mongodb
  DB_USERNAME: mongodb
  DB_NAME: parks  
kind: ConfigMap
metadata:  
  name: national-parks-app-config-map
